### ISSUE TITLE
Change Tags class to Tags namespace

### ISSUE THREAD

**Issue by felixfbecker** [jcchavezs/opentracing-php#2]
PHP supports namespaces and namespace constants, I don't see a reason why `Tags` should be a class

https://github.com/jcchavezs/opentracing-php/blob/master/src/OpenTracing/Ext/Tags.php

```php
namespace OpenTracing\Ext\Tags;

const SPAN_KIND = 'span.kind';
```

**Comment by jcchavezs** [comment]
Makes totally sense. I will change it soon. Feel free to open a PR if you feel so.
