### ISSUE TITLE
How to use OpenTracing tag constants?

### ISSUE THREAD

**Issue by beberlei** [jcchavezs/opentracing-php#29]
You have the file Tags.php, but how does one use it? Since autoloading only works for classes, it seems you have to speciifically require_once the file to be able to use it, which is difficult when using Composer that file is hidden far away in some directory. Its not in the composer.json as "file" to always autoload, so right now it seems the constants cannot be used.

1. Either use https://getcomposer.org/doc/04-schema.md#files to load the file always on every request.
2. Change Tags to be a class, so that the autoloader works when doing `OpenTracing\Ext\Tags::FOOBAR`.

**Comment by felixfbecker** [comment]
The file needs to be added `autoload.files`
