### ISSUE TITLE
Are classes for tags, log records, log fields etc really needed?

### ISSUE THREAD

**Issue by felixfbecker** [jcchavezs/opentracing-php#4]
In opentracing-javascript the API for logs allows to just pass a key/value hash:
```js
    log(keyValuePairs: { [key: string]: any }, timestamp?: number): this;
```
https://sourcegraph.com/github.com/opentracing/opentracing-javascript/-/blob/src/span.ts#L143-144

Tags can be set in the same way, just key/value as a hash or as two parameters.
Similarly, injecting/extracting works from any kind of key/value object.

PHP being similar to JavaScript as a dynamically typed language, what is the benefit of having classes for tags, log records and log fields? I don't see any benefit over just passing an associate array - is the user expected to write a subclass for every single event or tag that exists in the app?

**Comment by jcchavezs** [comment]
Using classes (which are actually VOs) makes them more cohesive as they are the only ones who knows what type they are and how they can be created. In addition, PHP 5.x is not typed so this makes sure the types are OK. What makes sense is to implement the logKV (which is actually a feature I did not include but that I already started working on based on https://github.com/opentracing/opentracing-go/blob/30dda9350627161ff15581c0bdc504e32ec9a536/span.go#L86). It is in the plan.

**Comment by felixfbecker** [comment]
I don't quite understand the benefit, what do you mean with "they are the only ones who knows what type they are"? What is the benefit of
```php
$span->logFields(
            Log::asString('event', 'soft error'),
            Log::asString('type', 'cache timeout'),
            Log::asInt('waited.millis', 1500))        
        )
```
vs
```php
$span->log([
  'event' => 'soft error',
  'type' => 'cache timeout',
  'waited.millis' => 1500
]);
```
as you would do in JS?
How is `Log::asInt('waited.milis', 1500)` any more type safe than `'waited.milis' => 1500`?
It looks like I am just boxing the int in a class.

**Comment by jcchavezs** [comment]
What if you pass `"type" => 123`? or `'waited.millis' => "the time"`, with VOs you can make sure that the information is the right one (right type and eventually right value) but I do agree that a more flexible `logKV` method should be also offered.

**Comment by felixfbecker** [comment]
So what prevents me to pass `Log::asInt('type', 123)` vs passing `'type' => 123`?

**Comment by jcchavezs** [comment]
That is a great question, I haven't noticed I pushed those changes. Have a look now at https://github.com/jcchavezs/opentracing-php/blob/master/src/OpenTracing/LogField.php#L46. BTW I just added this PR https://github.com/jcchavezs/opentracing-php/pull/9
